version: '2'
services:
    app:
        restart: always
        build: .
        command: "gunicorn -b 0.0.0.0:5000 ngl_example.app:app"
        environment:
            - FLASK_APP=ngl_example/app.py
        ports:
            - "5000:5000"
        volumes:
            - .:/usr/src/app
